= jumper

This project is for the purpose of learning how to make a basic game using
vanilla HTML, javascript, and css. It is a game where a user controls a
continuously jumping character left and right to land on randomly placed,
advancing platforms. If the character falls below the game stage, it is game
over. The higher the user goes, the higher the score.

== cloning repository

If you clone this repository, there are a few files that may need to be changed
to make sure that the application works correctly.

* /index.html
** Change the page name in the `title` element
+
[source,html]
----
...
<head>
  <meta charset="utf-8">
  <title>[NEW_APP_NAME]</title>
  ...
----
** Change the following `link` element
+
[source,html]
----
  <link rel="canonical" href="[NEW_URL_TO_APP_ROOT]" /> 
----
** Change the following `meta` elements
+
[source,html]
----
  ...
  <meta name="apple-mobile-web-app-title" content="[NEW_APP_NAME]">
  <meta name="application-name" content="[NEW_APP_NAME]" />
  ...
----

* /main.js
** Change the following in the `registerServiceWorker` function
+
[source,javascript]
----
  ...
  function registerServiceWorker() {
    navigator?.serviceWorker?.register(
      "[NEW_SUBFOLDER_OR_REMOVE_IF_ROOT]/serviceWorker.js",
      { scope: "[NEW_SUBFOLDER_OR_REMOVE_IF_ROOT]/" }
    )
  }
  ...
----

* /manifest.json
** Change the following properties
+
[source,json]
----
{
  "name": "[NEW_APP_NAME]",
  "short_name": "[NEW_APP_NAME]",
  ...
  "scope": "[NEW_SUBFOLDER_OR_REMOVE_IF_ROOT]/",
  ...
}
----

* /serviceWorker.js
** Change the following in the `registerServiceWorker` function
+
[source,javascript]
----
...
const APP_PREFIX = "[NEW_APP_NAME]"
const SUBFOLDER = `[NEW_SUBFOLDER_OR_REMOVE_IF_ROOT]`
...
----

== code development

This project was created using the free code editor
https://code.visualstudio.com[VS Code].

== images
=== edit image SVG source

Svg images in the `./asset-source` directory were created using the free vector
image editor https://inkscape.org[Inkscape].

=== edit raster images

Although it wasn't really used at the end, the free raster image editor
https://www.getpaint.net/[Paint.NET] can be used to edit PNG, JPG, and GIF
images.

=== favicon generation

Used https://realfavicongenerator.net/[Real Favicon Generator] to help create
some of the favicons and related resources need for the website to support
different browsers/operating systems. It supports PNG, JPG, and SVG sources.

=== compress SVG files

Used the online SVG compression tool https://www.svgminify.com/[SVG Minify] to
make all SVG images as small as possible.

For the best results with SVG Minify, I used Inkscape before uploading to:

. deleted all unnecessary objects and layers from the SVG
. select [Clean Up Document] from the [File] menu
. save as a new SVG with the file type as "Plain SVG (*.svg)"

=== compress PNG files

Used the online PNG compression tool https://tinypng.com/[TinyPNG] to make
all PNG images as small as possible.

== sounds
=== purchase music/sound effects

The sounds used in this project are from
https://audiojungle.net/[Audio Jungle]. You can download watermarked samples of
their sounds to test with and purchase the music after you have decided on what
sounds work best for your project.

=== edit audio files

Used https://www.audacityteam.org/[Audacity]

=== using sounds in JavaScript

https://www.w3schools.com/jsref/dom_obj_audio.asp[HTML DOM Audio Object]


== deploy
=== github pages

In VS Code's [Terminal] menu, click [Run Task...] and select
[Publish to github pages].

You can also run the following command in the terminal at the root of the
project.

[source,sh]
----
git subtree push --prefix website origin gh-pages
----

=== firebase
==== setup and installation

Firebase is a Google product that can be set up to host small applications for
free. The following steps assume your already have
https://docs.npmjs.com/downloading-and-installing-node-js-and-npm[nmp]
installed. Also, you can follow these steps to setup Firebase hosting,
but you may want to refer to the
https://firebase.google.com/docs/hosting[official instructions] for the
latest information. Alternatively, you can follow this
https://medium.com/@aleemuddin13/how-to-host-static-website-on-firebase-hosting-for-free-9de8917bebf2[nice article] that also goes over steps to connect your site to a custom domain.

. Install
+
[source,sh]
----
npm install -g firebase-tools
----

. Authenticate with Firebase
+
[source,sh]
----
firebase login
----

. Initialize project folder
+
[source,sh]
----
firebase init
----

. What to put in Firebase init prompts (your settings my differ)
.. Are you ready to proceed? - _Yes_
.. Which Firebase CLI features do you want to set up for this folder? - 
_Hosting: Configure and deploy Firebase Hosting sites_
.. First, let's associate this project directory with a Firebase project.
... Please select an option: _Create a new project_
... Please specify a unique project id - _[CHOOSE_A_PROJECT_ID]_
... What would you like to call your project? - _[CHOOSE_A_PROJECT_NAME]_
.. What do you want to use as your public directory? - _website_
.. Configure as a single-page app? - _y_
.. File website/index.html already exists. Overwrite? - _n_
.. Set up automatic builds and deploys with GitHub? _[UP_YOU_YOU]_

==== run locally
[source,sh]
----
firebase serve
----

==== deploy
[source,sh]
----
firebase deploy
----


== pwa
=== image sizes needed

https://love2dev.com/blog/easily-create-a-baseline-set-of-progressive-web-app-icons/[Easily Create a Baseline Set of Progressive Web App Icons]

=== publish to app stores

To publish your PWA to app stores you can use https://www.pwabuilder.com/pwabuilder[pwabuilder].

== credit

Software development:

https://github.com/noelitonoelito[Jeffrey Cardona]

Art work:

* Caleb character by SquidInk
* Zobie character by Darth Pangolin
* YoManBob! character by https://www.ailurusgraphics.com/[Robert Primeaux]

Sound:

* https://audiojungle.net/item/button-clicks/26591514[Menu sound] by https://audiojungle.net/user/alien-expo[Alien-Expo]
* https://audiojungle.net/item/game-jump/29146485[Jump sounds] by https://audiojungle.net/user/sounddivision[SoundDivision]
* https://audiojungle.net/item/cartoon-game-over/31553362[Game over sound] by https://audiojungle.net/user/phillipmariani[PhillipMariani]
* https://audiojungle.net/item/retro-game/21465199[Background music] by https://audiojungle.net/user/WormwoodMusic[WormwoodMusic]

== todo

* [ ] Add joystick control
* [ ] Add options to disable background music and all sounds
* [ ] Adjust platform advancing line when stage height changes
* [ ] Add jumping physics
* [ ] Add menu keyboard support
* [ ] Add Sophia character
* [ ] Keep track of personal high score
* [ ] Add narrow platforms
* [ ] Add breaking platforms
* [ ] Add horizontal moving platforms
* [ ] Add vertical moving platforms
* [ ] Add randomly moving platforms
* [ ] Add group high score board (having groups will limit cheating)
* [ ] Add About dialog

'''

* [x] _Add stage and a platform_
* [x] _Draw multiple platforms_
* [x] _Make platforms move down the stage_
* [x] _Place platforms at top of stage after they go below stage bottom_
* [x] _Add jumper character_
* [x] _Make jumper jump off of platforms_
* [x] _Add user keyboard control_
* [x] _Add scoreboard_
* [x] _Add game over_
* [x] _Add jumper image (Caleb), platform, and stage images_
* [x] _Add WASD controls_
* [x] _Make jumper upward draw advancement stop and only move the platforms
downward draw at the same speed the character is able to move up. This will
stop the jumper from moving past the top of the stage._
* [x] _Move stage background image as stage advances to give it a
parallax effect._
* [x] _Add touchscreen controls_
* [x] _Place platforms at random heights_
* [x] _Add full screen mode_
* [x] _Add restart game button on game over screen_
* [x] _Add character selection_
* [x] _Add Zobie character_
* [x] _Force portrait mode_
* [x] _Add favicon_
* [x] _Make game a PWA (progressive web app) that works in github pages._
* [x] _Add Bob character_
* [x] _Add game sounds_
* [x] _Add Noelito character_